services:
  payment-service:
    image: 'carbohz-payment:v3.0'
    container_name: payment-service
    environment:
      - 'SPRING'
    ports:
      - '8081:8081'
    networks:
      - app-network

  shop-service:
    image: 'carbohz-shop:v3.0'
    container_name: shop-service
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopdb'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/shopdb'
      - 'SPRING_R2DBC_USERNAME=postgres'
      - 'SPRING_R2DBC_PASSWORD=postgres'
      - 'PAYMENT_SERVICE_HOST=payment-service'
      - 'PAYMENT_SERVICE_PORT=8081'
    depends_on:
      postgres:
        condition: service_healthy
      payment-service:
        condition: service_started
    ports:
      - '8080:8080'
      - '5005:5005'
    networks:
      - app-network

  postgres:
    image: 'postgres:17.4'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=shopdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shopdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge