services:
  intershop:
    image: 'carbohz-intershop:v2.0'
    container_name: intershop_app
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/intershopdb'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/intershopdb'
      - 'SPRING_R2DBC_USERNAME=postgres'
      - 'SPRING_R2DBC_PASSWORD=postgres'
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - '8080:8080'
    networks:
      - app-network

  postgres:
    image: 'postgres:17.4'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=intershopdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d intershopdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

networks:
  app-network:
    driver: bridge