services:
  postgres:
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=intershopdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d intershopdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
