services:
  payment-service:
    image: 'carbohz-payment:v4.0'
    container_name: payment-service
    environment:
      - 'BALANCE_SUM=500000'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5432/paymentdb'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://postgres-payment:5432/paymentdb'
      - 'SPRING_R2DBC_USERNAME=postgres'
      - 'SPRING_R2DBC_PASSWORD=postgres'
      - 'KEYCLOAK_ISSUER_URL=http://keycloak:8080/realms/master'
    depends_on:
      postgres-payment:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    ports:
      - '8081:8081'
    networks:
      - app-network

  postgres-payment:
    container_name: postgres-payment
    image: 'postgres:17.4'
    environment:
      - 'POSTGRES_DB=paymentdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5433:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d paymentdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  shop-service:
    image: 'carbohz-shop:v4.0'
    container_name: shop-service
    environment:
      - 'SPRING_PROFILES_ACTIVE=prod'
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shopdb'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=postgres'
      - 'SPRING_R2DBC_URL=r2dbc:postgresql://postgres:5432/shopdb'
      - 'SPRING_R2DBC_USERNAME=postgres'
      - 'SPRING_R2DBC_PASSWORD=postgres'
      - 'PAYMENT_SERVICE_HOST=payment-service'
      - 'PAYMENT_SERVICE_PORT=8081'
      - 'REDIS_HOST=redis'
      - 'REDIS_PORT=6379'
      - 'CACHING_TTL_ITEMS=60'
      - 'CACHING_TTL_ITEM=60'
      - 'KEYCLOAK_ISSUER_URL=http://keycloak:8080/realms/master'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      payment-service:
        condition: service_started
      keycloak:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '5005:5005'
    networks:
      - app-network

  postgres:
    image: 'postgres:17.4'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=shopdb'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d shopdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  redis:
    image: redis:8-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    networks:
      - app-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    container_name: keycloak
    ports:
      - '18080:8080'
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    command: start-dev --import-realm --verbose
    healthcheck:
      test: ['CMD-SHELL', '[ -f /tmp/HealthCheck.java ] || echo "public class HealthCheck { public static void main(String[] args) throws java.lang.Throwable { java.net.URI uri = java.net.URI.create(args[0]); System.exit(java.net.HttpURLConnection.HTTP_OK == ((java.net.HttpURLConnection)uri.toURL().openConnection()).getResponseCode() ? 0 : 1); } }" > /tmp/HealthCheck.java && java /tmp/HealthCheck.java http://localhost:9000/health/live']
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - app-network

networks:
  app-network:
    driver: bridge