spring:
  application:
    name: payment
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:18080/realms/master # Адрес сервера авторизации для получения токена
server:
  port: 8081
springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled:
      true
balance:
  sum: ${BALANCE_SUM:500000}